### ISSUE TITLE
Getting warning for Calligraphy in release build

### ISSUE THREAD

**Issue by KunalShivnekar** [freshdesk/freshchat-android#1]
Hi, 
The Proguard rules for Calligraphy has a typo. It should be "chris**j**enx" in place of "chris**h**enx".

**Comment by tryprasannan** [comment]
@KunalShivnekar Thanks for reporting this. We have fixed & released this in [Freshchat SDK version 1.1.1](https://github.com/freshdesk/freshchat-android/releases/tag/1.1.1)
