### ISSUE TITLE
Can't get generated restoreId

### ISSUE THREAD

**Issue by yarKH** [freshdesk/freshchat-android#11]
sdk 1.3.0

1. Freshchat.getUser().getRestoreId() always return ""
2. BroadcastReceiver onReceive never fired

```java
String restoreId = loadRestoreId();

Freshchat freshchat = Freshchat.getInstance(context);

if (TextUtils.isEmpty(restoreId)) {
    freshchat.identifyUser(getUid(), null);  // removing this line changes nothing

    String newRestoreId = freshchat.getUser().getRestoreId();
    if (TextUtils.isEmpty(newRestoreId)) {
        receiveFreshchatRestoreId();
    } else {
        saveRestoreId(newRestoreId);
    }
} else {
    freshchat.identifyUser(firebaseUser.getUid(), restoreId);
}

private void receiveFreshchatRestoreId() {

    IntentFilter intentFilter = new IntentFilter(Freshchat.FRESHCHAT_USER_RESTORE_ID_GENERATED);

    final BroadcastReceiver broadcastReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            String restoreId = Freshchat.getInstance(context).getUser().getRestoreId();
            LocalBroadcastManager.getInstance(AtroposApplication.getAppContext()).unregisterReceiver(this);
        }
    };

    LocalBroadcastManager.getInstance(AtroposApplication.getAppContext()).registerReceiver(broadcastReceiver, intentFilter);
}
```

**Comment by yarKH** [comment]
> 1. The restore id is typically generated only after user has sent a message.

It works. Received broadcast message right after message sent. It should be mentioned in docs.

Thank you for your help!

**Comment by MaxDunzo** [comment]
How many times do you send that Broadcast event ?? . 
is it only once ??. . if i miss the event somehow . . then the only option is to get it through Freshchat.getInstance(getApplicationContext()).user.restoreId    ????

**Comment by mallikarjun046** [comment]
broarcast receiver is not triggering  after the message sent.

**Comment by mallikarjun046** [comment]
BroadcastReceiver onReceive never fired

**Comment by rameshfreshworks** [comment]
@mallikarjun046  Where are you registering the broadcast receiver for restoreId? 
We would suggest doing it in your Application class.

**Comment by mallikarjun046** [comment]
Hi
It is generated but it is not happening first time of the chat
conversation. It is happening 2nd time chat conversation.

Thank you

**Comment by mallikarjun046** [comment]
Loading indefinitely Sometimes

**Comment by rameshfreshworks** [comment]
Hi @mallikarjun046 , Please elaborate your query as when and where exactly are you facing indefinite loading problem.

**Comment by mallikarjun046** [comment]
when the app launch first time. that time chat conversation is showing . i am facing this issue after relaunching the application. and it's happening randomly.

**Comment by rameshfreshworks** [comment]
@mallikarjun046 Okay. we have the demo apps covering different use cases in this project under sample module. Please go through them and make required changes as per the demo app code. 
If you still face the issue,  please reach out to support@freshchat.com with Freshchat integration code details. We are happy to help.
