### ISSUE TITLE
Adding 350 kb to apk

### ISSUE THREAD

**Issue by manishandroid** [freshdesk/freshchat-android#12]
I have integrated FreshChat in my app and when I analyzed my release apk, analyzer says that Fresh Chat is adding 350kb to my apk. I would recommend making lib size as smaller as possible. This is not an issue but can be taken as an enhancement. 

![screen shot 2018-01-31 at 1 29 38 am](https://user-images.githubusercontent.com/4254384/35588353-671b98ba-0626-11e8-9423-3ab064460bf7.png)

**Comment by tryprasannan** [comment]
@manishandroid Thanks for your feedback. We believe Freshchat is one of the smallest Chat SDKs around, in terms of size, among ones with comparable features. That said if you have any specific feedback or improvements in mind, please feel free to share.
