### ISSUE TITLE
Notifications not showing in Android O

### ISSUE THREAD

**Issue by cpauwels** [freshdesk/freshchat-android#13]
Hi,

Android O introduced new notification channels, but Freshchat doesn't support them and as such notifications are not shown. 

What is the channel ID that Freshchat uses? That way I can manually create the notification channel before calling `Freshchat.getInstance(applicationContext).setNotificationConfig(notificationConfig)`

Here is the error I get: `Notification: Use of stream types is deprecated for operations other than volume control`

Thanks,

Charles

**Comment by tryprasannan** [comment]
@cpauwels Recommend using the version 1.3.1 which adds out of the box support for notification channels, the notification channel names can be customised via strings.xml.
