### ISSUE TITLE
Please provide a pre-built APK in the repo

### ISSUE THREAD

**Issue by AdityaAnand1** [freshdesk/freshchat-android#16]

**Comment by tryprasannan** [comment]
@AdityaAnand1 If you want to checkout the chat experience, you can download our agent app from the PlayStore or the Appstore and try it out by clicking on support from the left nav drawer. We don't ship a pre-built apk as one can't experience the product fully without also having access to agent credentials to the account the app is connected to.

For a basic working sample, you can just key in the app id and app key in the “DemoActivity” in the sample included in this repo and run the app.

**Comment by AdityaAnand1** [comment]
Yes, that was my point. To make it easier for potential freshdesk customers to check out what the android sdk "feels" like without having to go through a long setup.

Not super important, but I am currently trying to decide which provider to go with and it's just a matter of who can convince me first.  A pre-built apk bundled with demo API keys would go a long way towards making my life easier :)

**Comment by tryprasannan** [comment]
As pointed out earlier, you can signup and check out the support section in the team member/agent mobile apps on Android & iOS (which uses Freshchat SDK for support). 
You don't have to go through any setup/development effort at all for this.
