### ISSUE TITLE
Notification sound doesn't play on some devices

### ISSUE THREAD

**Issue by Alexey-** [freshdesk/freshchat-android#17]
I'm receiving reports from testers that freshchat notification sound doesn't play.
It seems like samsungs with OS 6.0 are affected, although I only had 2 reports.
What's more important is that while freshchat notifications are mute, normal notifications show up with sound inside the very same application. So the tester responds to his request in freshchat - no sound. Immediately sends himself another push from our server - hears the sound.

Here's how freshchat is configured:

		final FreshchatConfig freshchatConfig = new FreshchatConfig("xxx","xxx");
		FreshchatNotificationConfig freshchatNotificationConfig = new FreshchatNotificationConfig();
		freshchatNotificationConfig.setLargeIcon(NotificationStyle.getLargeIcon());
		freshchatNotificationConfig.setSmallIcon(NotificationStyle.getSmallIcon());
		freshchatNotificationConfig.setNotificationSoundEnabled(true);
		freshchatNotificationConfig.setPriority(Notification.PRIORITY_MAX);

		final Freshchat freshchat = Freshchat.getInstance(this);
		freshchat.init(freshchatConfig);
		freshchat.setNotificationConfig(freshchatNotificationConfig);

Here's how we show our own notifications:

        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(context, NOTIFICATION_CHANNEL_ID);
        notificationBuilder
                .setSmallIcon(NotificationStyle.getSmallIcon())
                .setLargeIcon(NotificationStyle.getLargeIcon())
                .setColor(ContextCompat.getColor(context, NotificationStyle.getColor()))
                .setContentTitle(context.getString(NotificationStyle.getContentTitle()))
                .setContentText(message)
                .setTicker(tickerText)
                .setAutoCancel(true)
                .setContentIntent(resultPendingIntent)
                .setDefaults(Notification.DEFAULT_LIGHTS);

        notificationBuilder.setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION));

        long[] vibratePattern = new long[NotificationStyle.getVibratePattern().length];
        for (int i = 0; i < NotificationStyle.getVibratePattern().length; i++) {
            vibratePattern[i] = NotificationStyle.getVibratePattern()[i];
        }
        notificationBuilder.setVibrate(vibratePattern);

        NotificationManager notificationManager = (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);

        if (notificationManager != null) {
            notificationManager.notify(serviceCode, notificationId, notificationBuilder.build());
        }

At this point I'm not even sure how can I report this bug properly. 
Maybe you could send me the code which shows notification inside your sdk, and I'll build a minimal working app and send it to the tester who has this problem?

**Comment by Alexey-** [comment]
Correction: bug occurs on Sony devices, not Samsung.
OS version 6.0.

**Comment by tryprasannan** [comment]
@Alexey- Sorry for the delayed response. Can you try explicitly setting the notification tone to see if it makes any difference ?
`freshchatNotificationConfig.setNotificationSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION));`

**Comment by Alexey-** [comment]
@tryprasannan Will try it. Since I need to make a new build and then send it to the tester with sony phone, this may take some time.

**Comment by tryprasannan** [comment]
@Alexey- Sure, thanks.

**Comment by Alexey-** [comment]
@tryprasannan It works.
After I've added `freshchatNotificationConfig.setNotificationSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION));` tester can now hear sound for all freshchat notifications on all devices.

**Comment by tryprasannan** [comment]
@Alexey- Thanks for the confirmation. We'll get the default behaviour fixed.

**Comment by tryprasannan** [comment]
@kotya341 The original issue is the default tone not being set out of the box. Looks like yours is different. On the same device if you pass the same tone to a sample notification, does it play?  If sample notification plays the tone and Freshchat SDK doesn't, can you share more information about the device model and OS version etc?

**Comment by tryprasannan** [comment]
@Alexey This has been fixed and released as part of [SDK version 1.5.0](https://github.com/freshdesk/freshchat-android/releases/tag/1.5.0)

**Comment by kusumakara** [comment]
Notification sound doesn't play on SAMSUNG devices. While normal GSM calls are going on.
Android Version: 8.1.0
