### ISSUE TITLE
SDK 1.3.3 , Android Oreo , translation issue 

### ISSUE THREAD

**Issue by hohoboho** [freshdesk/freshchat-android#18]
I have bilingual app , and I create two XML files , for the two languages (English and Arabic) . The problem is that when the user switch language in Android 8.0 , the translation from English to Arabic does not appear for those Freshchat keys: 

 - "freshchat_activity_title_channel_list", "freshchat_typically_replies_within_a_minute", "freshchat_typically_replies_within_x_minutes" , "freshchat_typically_replies_within_an_hour" , "freshchat_typically_replies_within_2_hours" , "freshchat_typically_replies_within_few_hours" , "freshchat_placeholder_minutes" , "freshchat_chat_message_composer_hint" , "freshchat_chat_capture_from_camera" , "freshchat_chat_select_from_gallery" , "freshchat_default_agent_name" .

 Is that SDK issue , or something with the Android 8.0 . Thank you in advance for any help . 
Here is a chunk from my code if you want to test that (the Arabic strings) : 

    <string name="freshchat_activity_title_channel_list">محادثات</string>
    <string name="freshchat_typically_replies_within_a_minute">عادة الرد في غضون دقيقه</string>
    <string name="freshchat_typically_replies_within_x_minutes">دقائق {{minutes}} عادة الرد خلال</string>
    <string name="freshchat_typically_replies_within_an_hour">عادة الرد في غضون ساعه</string>
    <string name="freshchat_typically_replies_within_2_hours">عادة الرد في غضون ساعتين</string>
    <string name="freshchat_typically_replies_within_few_hours">عادة الرد في غضون بضع ساعات</string>
    <string name="freshchat_placeholder_minutes">{{minutes}}</string>
    <string name="freshchat_chat_message_composer_hint">اكتب رسالتك</string>
    <string name="freshchat_chat_capture_from_camera">التقط صورة</string>
    <string name="freshchat_chat_select_from_gallery">التحميل من الاستوديو</string>
    <string name="freshchat_default_agent_name">الدعم</string>

**Comment by divanova123456** [comment]
This is not working yet (sdk: 1.3.4)

**Comment by tryprasannan** [comment]
@hohoboho @divanova123456

1. Can you confirm if this happens for all strings or only a subset of strings ?
2. Can you confirm if this behaviour is seen only for specific languages/locales only or do you see this for all other languages/locales ?
3. Do you observe different behaviour on different OS versions? Or with different target version ?

**Comment by hohoboho** [comment]
Hi there ,
I can confirm that : 
1. This happens for only a subset of strings , thats why I post the keys from your strings.xml file .
2. This behaviour is seen , when the app uses Arabic language specifically , the simulators or devices for testing are with English language .
3. It happens only in Android 8.0 and above .

**Comment by tryprasannan** [comment]
@hohoboho Thanks for the information, we'll get this checked from our side and update.

**Comment by MuthuFD** [comment]
@hohoboho We were unable to reproduce this issue. Can you share a test version of your app where we can test this out.

Please email it to support@freshchat.com

**Comment by hohoboho** [comment]
@MuthuFD Hi there , 
I found a way to make it work : 
1. I change the device local to Arabic 
2. App language is in Arabic 
, everything is fine . 
But , let me suggest , to make it possible for the dev (I am just a QA) , to send you param for the language , and do not take it from the device locale . Just a case scenario : old device , or device that does not support the app language , user install the app , change the app locale to his language , and your staff stack . Think about it . Thank you for the efforts , you can close this case . 

p.s. I hope you rethink the logic how Freshchat took the language .

**Comment by Binusz** [comment]
This is serious problem. 
We can change app locale programmatically below Android 8.0 . However, above 8.0, user have to change device language...
