### ISSUE TITLE
registered broadcaster not triggerring when there is new incoming message

### ISSUE THREAD

**Issue by kmteck** [freshdesk/freshchat-android#20]
I Have Written a BroadcastReceiver to be triggered when there is new incoming message, but it is triggered only when i explicitly open conversation screen 
(Freshchat.showConversations(getApplicationContext());) 

@Override
    public void onReceive(final Context context, Intent intent) {
        Freshchat.getInstance(context).getUnreadCountAsync(new UnreadCountCallback() {
            @Override
            public void onResult(FreshchatCallbackStatus freshchatCallbackStatus, final int i) {
                sendNotification(context, i);
            }
        });
    }

this is my code in onReceive() code

I'm registering receiver in onStart() of BaseActivity (all my activity extends this) and unregistering at receiver onDestroy of BaseActivity

**Comment by tryprasannan** [comment]
@kmteck The receiver will trigger when ever a new message is received. For ideal experience, we recommend implementing push notifications in your app, otherwise updates might be delayed.
