### ISSUE TITLE
getUnreadMessagesCount doesn't return any response 

### ISSUE THREAD

**Issue by kotya341** [freshdesk/freshchat-android#24]
we have a logic when user have to be notified all the time when new message is coming.
so I put an `getUnreadMessagesCount` call `onStart` of my fragment and to the push notification method 

the problem is when user rotates the device we do the call, but sometimes (depending on a device it can be 30% of the time) we got nothing from server

**Comment by tryprasannan** [comment]
@kotya341 The calls may be rate limited if its being called too often. If your aren't already using push notifications with the SDK, we recommend setting up push notifications for quicker updates.

**Comment by MuthuFD** [comment]
@kotya341 We have made some improvements to our getUnreadMessagesCount API.

Please update to our latest SDK version.

Closing this issue. If you are still facing this issue in our latest version, feel free to reopen
