### ISSUE TITLE
Application Crash Happen using Freshchat sdk 1.5.0 android oreo device

### ISSUE THREAD

**Issue by hariharanc** [freshdesk/freshchat-android#28]
In my application we are using fresh chat android sdk 1.5.0 ,So i followed all the implementation steps mentioned in blog but android oreo device my application keep on crash happen,Please refer the below error log  received in my android studio.

> 'Background start not allowed: service Intent { cmp=/com.freshchat.consumer.sdk.service.FreshchatService } to /com.freshchat.consumer.sdk.service.FreshchatService from pid=7996 uid=10444 pkg=
I/ActivityManager:   Force stopping service ServiceRecord{6a5ba6f u0 /com.freshchat.consumer.sdk.service.FreshchatService}
I/Telecom: DefaultDialerCache: Refreshing default dialer for user 0: now com.google.android.dialer: DDC.oR@Cy0
W/ActivityManager: Scheduling restart of crashed service /com.freshchat.consumer.sdk.service.FreshchatService in 1000ms'

Kindly do the needful.

**Comment by tryprasannan** [comment]
This should not be an actual crash. Are you seeing this otherwise ? We log it to log cat when this happens, do you see the log? That said we'll work on improving this experience.

**Comment by hariharanc** [comment]
@tryprasannan this issue happen only in release mode android Oreo but it's work fine in debug mode..

**Comment by tryprasannan** [comment]
@hariharanc Can you share info on what is your app's `targetSdkVersion` and the dependency rgaph?

**Comment by hariharanc** [comment]
@tryprasannan its our app proguard rule issue after removing that rule now freshchat work fine in android Oreo device thanks...

**Comment by tryprasannan** [comment]
@hariharanc Nice to know its working now. Thanks for the confirmation.

**Comment by viddin18** [comment]
@hariharanc I am facing the same issue as well. Can you let us know which proguard rule causes this issue ?
