### ISSUE TITLE
Add changelogs when updating SDK version.

### ISSUE THREAD

**Issue by gnumilanix** [freshdesk/freshchat-android#3]
It's really annoying to find breaking changes after updating the Freshchat SDK. The first time I updated the Freshchat SDK it broke all theme customization, now the `FreshchatUser.setExternalId()` has been removed It would give us heads up on what has changed including:

- Breaking Changes
- Enhancements
- Bug Fixes

A really good example of this is done by [Realm](https://github.com/realm/realm-java/blob/master/CHANGELOG.md).

**Comment by tryprasannan** [comment]
Thanks for suggestion. We'll ensure we document breaking changes in a section in our release notes or a change log.

**Comment by Abdelrhmanwalid** [comment]
Any updates on this?

**Comment by tryprasannan** [comment]
@gnumilanix Please find the changelog here for changes made in various versions of SDK. https://github.com/freshdesk/freshchat-android/blob/master/CHANGELOG.md
