### ISSUE TITLE
Difference between campaign and conversation notification channels

### ISSUE THREAD

**Issue by Alexey-** [freshdesk/freshchat-android#31]
Hello,

Freshchat creates the following notification channels on Android 8+:
freshchat_campaign_notification_channel_name
freshchat_conversation_notification_channel_name

As far as I understand, conversation channel is for chat.
What campaign channel is for?

I want to provide a reasonable localization but I don't understand what types of notifications show in this channel.

**Comment by MuthuFD** [comment]
Hi Alexey. 

**freshchat_campaign_notification_channel_name** is the Notification Channel name for message received through **In-App Campaigns**

For more details, refer [In-App Campaigns](https://support.freshchat.com/support/solutions/articles/232625)

I'm closing this. Feel free to contact us @ support@freshchat.com
