### ISSUE TITLE
Cant compile Freshchat to Phonegap

### ISSUE THREAD

**Issue by knikolou** [freshdesk/freshchat-android#32]
Dear sir after installation of the plugin i am getting this error when compile to phonegap
When i remove the installation it works ok
i have install this
a)gap:plugin spec="https://github.com/techaffinity/freshchat-phonegap.git" source="git" />
b)
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() { 
window.Freshchat.init({
    	appId       : "xxxxxxxxx",
    	appKey      : "xxxxxxxx",
    });        

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.+.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.+.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by MuthuFD** [comment]
Hi @knikolou, Freshchat Phonegap plugin is developed and maintained by a Third Party.

Please raise your issue here - https://github.com/techaffinity/freshchat-phonegap/issues

If your issue is not sorted, please reach out to us through support@freshchat.com.
