### ISSUE TITLE
Sometimes user email and name are not displayed in conversation

### ISSUE THREAD

**Issue by Alexey-** [freshdesk/freshchat-android#33]
In rare cases, some users will not have email and name displayed in freshchat admin panel where you talk to them. It works 99% of the time, but once in a while we get a user without an email.

I've started investigating this issue and I thought that there is a bug in my app. As it turned out I do have a bug in my app - if user email is null, app will crash before opening freshchat. Which means that I'll always supply freshchat with non-null email:

```
Freshchat freshchat = Freshchat.getInstance(context.getApplicationContext());
FreshchatUser freshchatUser = freshchat.getUser();
freshchatUser.setFirstName(customer.getFirstName());
freshchatUser.setLastName(customer.getLastName());
freshchatUser.setEmail(customer.getEmail());
freshchat.identifyUser(customer.getExternalId(), null);
freshchat.setUser(freshchatUser);
Freshchat.showConversations(context);
```

My question is: how does freshchat handle FreshchatUser? 
Do you retry network request with user data if the first one fails? Could it be caused by a random network error?
Do you retry network request with user data if I supply exactly the same data as before (same name, email, etc.)?

**Comment by tryprasannan** [comment]
@Alexey- 
1) Freshchat SDK does have auto retry for failed network requests, so you don't have to provide same data again. 
2) Even if you provide same data again, SDK has the ability to track the uploaded fields and sends only if new information is present
If this happens on your device and can help with steps and logs for this issue, please share here or email it to `support@freshchat.com`

**Comment by Alexey-** [comment]
It doesn't happen on my device unfortunately. It seems like it's a random bug that's very hard to reproduce.
In any case, I'm adding the following condition right before the code in my first snippet:

```
if (TextUtils.isEmpty(customer.getEmail())) {
    throw new RuntimeException("Empty customer email");
}
```

If the app starts to crash now, then it's my problem. If it doesn't crash and we still continue to receive messages without email, then there's a bug in your code.

I'll let you know how it goes in a couple of weeks.

**Comment by tryprasannan** [comment]
@Alexey- Sure. Thanks. Closing this for now. If this continues to happen, please respond here.

**Comment by Alexey-** [comment]
I forgot about this problem for a while, but it looks like it's still there.

Right now, my code looks like this:
```
if (TextUtils.isEmpty(customer.getEmail())) {
	throw new RuntimeException("Empty customer  email");
}

Freshchat freshchat = Freshchat.getInstance(context.getApplicationContext());
FreshchatUser freshchatUser = freshchat.getUser();

freshchatUser.setFirstName(customer.getFirstName());
freshchatUser.setLastName(customer.getLastName());
freshchatUser.setEmail(customer.getEmail());
freshchat.identifyUser(customer.getExternalId(), null);
freshchat.setUser(freshchatUser);

Freshchat.showConversations(context);
```

Customer is final, customer.email is final too. Since the app doesn't crash, email is definitely not empty. 

And yet we continue to receive messages without any user information from this version of the app. 
I was able to find 4 buggy users this week (amongst few hundreds)

**Comment by PoriLisa** [comment]
Map<String, String> userMeta = new HashMap<String, String>();
userMeta.put("userLoginType", "Facebook");
userMeta.put("city", "SpringField");
userMeta.put("age", "22");
userMeta.put("userType", "premium");
userMeta.put("numTransactions", "5");
userMeta.put("usedWishlistFeature", "yes");

//Call setUserProperties to sync the user properties with Freshchat's servers
Freshchat.getInstance(getApplicationContext()).setUserProperties(userMeta);
i have set this but i am unable to set the user details . how do i do it
