### ISSUE TITLE
An error with chat tags

### ISSUE THREAD

**Issue by gilshallem** [freshdesk/freshchat-android#35]
```
 ConversationOptions opts = new ConversationOptions();
 opts.filterByTags(Arrays.asList("whatsapp_exporter"),null);
 Freshchat.showConversations(getApplicationContext(),opts);
```
In the first time it ignores the tags, second time it uses them and open a new conversation

**Comment by tryprasannan** [comment]
Hi @gilshallem,
1) Can you confirm if filtering by tags is the only way your users reach support ? Or are there other mechanisms.
2) When (in the life cycle of your app) does your app invoke Freshchat.init() ?

**Comment by gilshallem** [comment]
Hi,
Thank you for replying. 
1. Definitely, only one place.
2. On the application oncreate

**Comment by MuthuFD** [comment]
Hi @gilshallem ,

Can you please share obfuscated version of your application to us? We will debug this and get back to you.

Please send the APK to support@freshchat.com.

**Comment by MuthuFD** [comment]
@gilshallem We are closing this issue. Please share obfuscated version of your application to support@freshchat.com. We will debug and get back to you.

**Comment by gilshallem** [comment]
Hi Again,
I am sorry I didn't have time to create an obfuscated version.

here is the code:
from the build.gradle:

api 'com.github.freshdesk:freshchat-android:1.5.3'

ConversationOptions opts = new ConversationOptions();
List<String> tags = Global.getInstance().getFreshChatTags();
if (tags!=null)
    opts.filterByTags(tags,null);

Freshchat.showConversations(getApplicationContext(),opts);
 overridePendingTransition(R.anim.enter_from_right,R.anim.exit_to_left);

Global.getInstance().getFreshChatTags() *is never null*

@Override
public List<String> getFreshChatTags() {
    return Arrays.asList("facebook_exporter");
}

private void addInfoToUser() {
    // Set the app
    try {
        Freshchat.getInstance(getApplicationContext()).setUserProperty("App",getString(R.string.app_name)
);
    } catch (Exception e)
    {
        e.printStackTrace();
    }

    // Set the order id
    try {
        String orderId = BillingHelper.getInstance().getOrderId();
        if (!TextUtils.isEmpty(orderId))
            Freshchat.getInstance(getApplicationContext()).setUserProperty("Order",orderId
);
    } catch (Exception e)
    {
        e.printStackTrace();
    }

    // set android ID
    try {
        String androidId = Utils.getDeviceId(this);
        if (!TextUtils.isEmpty(androidId))
            Freshchat.getInstance(getApplicationContext()).setUserProperty("Device
ID",androidId );
    } catch (Exception e)
    {
        e.printStackTrace();
    }

    // set default sms app
    try {
        String defaultSMSApp = Utils.getDefaultSMSPackage(this);
        if (!TextUtils.isEmpty(defaultSMSApp))
            Freshchat.getInstance(getApplicationContext()).setUserProperty("Default
SMS App",defaultSMSApp );
    } catch (Exception e)
    {
        e.printStackTrace();
    }

    try {

    //set the locale
    Freshchat.getInstance(getApplicationContext()).setUserProperty("Locale",Locale.getDefault().toString()
);
    } catch (Exception e)
    {
        e.printStackTrace();
    }


}

from APP.java -> onCreate() :

private void initFreshchat(String freshchatAppId, String freshchatAppKey) {

    Freshchat.setImageLoader(new FreshchatImageLoader() {
        @Override
        public void load(@NonNull FreshchatImageLoaderRequest
freshchatImageLoaderRequest, @NonNull ImageView imageView) {

            RequestCreator loader =
Picasso.get().load(freshchatImageLoaderRequest.getUri());
            if (freshchatImageLoaderRequest.getTransformToApply() ==
FreshchatImageLoaderRequest.TransformType.CIRCULAR)
                loader.transform(new CircleTransform());
            loader.resize(freshchatImageLoaderRequest.getTargetWidth(),
freshchatImageLoaderRequest.getTargetHeight());
            if (freshchatImageLoaderRequest.shouldMaintainAspectRatio()) {
                loader.centerInside();
            }
            loader.into(imageView);

        }

        @Nullable
        @Override
        public Bitmap get(@NonNull FreshchatImageLoaderRequest
freshchatImageLoaderRequest) {

            RequestCreator loader =
Picasso.get().load(freshchatImageLoaderRequest.getUri());
            if (freshchatImageLoaderRequest.getTransformToApply() ==
FreshchatImageLoaderRequest.TransformType.CIRCULAR)
                loader.transform(new CircleTransform());
            loader.resize(freshchatImageLoaderRequest.getTargetWidth(),
freshchatImageLoaderRequest.getTargetHeight());
            if (freshchatImageLoaderRequest.shouldMaintainAspectRatio()) {
                loader.centerInside();
            }
            try {
                return loader.get();
            } catch (IOException e) {
                return null;
            }
        }

        @Override
        public void fetch(@NonNull FreshchatImageLoaderRequest
freshchatImageLoaderRequest) {
            get(freshchatImageLoaderRequest);
        }
    });
    FreshchatConfig freshchatConfig = new
FreshchatConfig(freshchatAppId, freshchatAppKey);
    freshchatConfig.setCameraCaptureEnabled(true);
    freshchatConfig.setGallerySelectionEnabled(true);

    //freshchatConfig.setTeamMemberInfoVisible(true);

    Freshchat.getInstance(getApplicationContext()).init(freshchatConfig);
    FreshchatNotificationConfig notificationConfig = new
FreshchatNotificationConfig()
            .setNotificationSoundEnabled(true)
            .setSmallIcon(R.drawable.support_icon)
            .setLargeIcon(R.drawable.support_logo)

            .setPriority(NotificationCompat.PRIORITY_HIGH);


    Freshchat.getInstance(getApplicationContext()).setNotificationConfig(notificationConfig);


}

**Comment by davidecheli** [comment]
Any news regading this problem?

I'm still having this problem.

**Comment by gilshallem** [comment]
Hi david, thank you for getting back to me. I found the source of the issue
in my code. I was runing it from a different section of my code. From the
one i tought. It works well now
