### ISSUE TITLE
How to use Freshchat with Fragment?

### ISSUE THREAD

**Issue by Sabareeshboopathi** [freshdesk/freshchat-android#37]
Hi Guys,

I am having Bottom navigation with different fragments. I want to load freshchat conversation in to Frame Layout. Anybody able to help me?

Thanks,
Sabareesh Boopathi

**Comment by MuthuFD** [comment]
Hi @Sabareeshboopathi , All Freshchat SDK screens are full screen activities. They can not be embedded inside a FrameLayout like a Fragment.
