### ISSUE TITLE
FAQs not loading on release build

### ISSUE THREAD

**Issue by Slake07** [freshdesk/freshchat-android#39]
I had integrated freshchat with my application. While running in debug build, my FAQs listed properly. but when i run release build, FAQs not listed and also not showing any errors in logs.

**Comment by MuthuFD** [comment]
Hi @Slake07 , 
I think you have contacted us thru support@freshchat.com also. 
Please share us your release version of your apk. We will debug and help you out.

**Comment by MuthuFD** [comment]
Hi @Slake07 ! 
We saw that JSONObject was obfuscated. 
Adding rules to retain org.json. package in your proguard rules will resolve the issue.
​
-keep class org.json.** { *; }
-keep interface org.json.** { *; }
