### ISSUE TITLE
Add support for metadata when launching conversation

### ISSUE THREAD

**Issue by gnumilanix** [freshdesk/freshchat-android#41]
As a provider for connecting business with users, Freshchat has been missing a feature to provide, **metadata when launching conversation**.

Having been integrated with Freshchat for almost 2 years now, this has been extremely frustrating for our customers and support team. We to ask the user for the order id and the user needs to provide it. Our user thinks we are stupid because, we launched the conversation from the order detail and yet, we are asking for the order id.

Yes there's smart plug but, the feature sample assumes that each user can only have an ongoing order. But, that's not a reality in many of the e-commerce. If a user has multiple order, we will have the same issue as mentioned above.

Not to mention, one of the key selling points in the home page is "_Get all the context you need to sell smarter_"

**Comment by MuthuFD** [comment]
Thanks for your feedback @gnumilanix .
We will look to incorporate this use case into our product.

**Comment by MuthuFD** [comment]
We are working on a feature that will be helpful in this scenario. We will update here after release.

**Comment by PoriLisa** [comment]
hello , how to add meta data of an user and showing them their problem per order like zomato .

**Comment by rameshfreshworks** [comment]
Hi all,
We are happy to inform you that we support logging user events from v3.1.0.
Refer section 3.3 in our documentation for more details 
https://support.freshchat.com/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps

**Comment by rameshfreshworks** [comment]
Freshchat now supports logging metadata from v3.1.0 hence closing this issue.
