### ISSUE TITLE
Can't take photo with camera

### ISSUE THREAD

**Issue by gyatsina** [freshdesk/freshchat-android#42]
I can't take photo with camera in Freshchat, though I have configured FileProvider in Manifest
What else could be wrong?
I have successfully uploaded photo from gallery, it worked. Then I tries camera - no success.

the error I get on the screen is: "Failed to access camera! Error:351"
(though I have camera permission in Manifest.)

the error I get in log is:
E/FRESHCHAT: Exception on motorola Nexus 6 Android API 7.1.1 (25) >>>>> Failed to find configured root that contains /storage/emulated/0/Android/data/com.packagename/cache/freshchat/tmp/JPEG_15542118824381155307849.jpg  
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.packagename/cache/freshchat/tmp/JPEG_15542118824381155307849.jpg

**Comment by evandavid** [comment]
Hi, i found a solution for this

in res/xml/freshchat_file_provider_paths.xml

write
`<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path
        name="external"
        path="." />
    <external-files-path
        name="external_files"
        path="." />
    <cache-path
        name="cache"
        path="." />
    <external-cache-path
        name="external_cache"
        path="." />
    <files-path
        name="files"
        path="." />
</paths>`

**Comment by gyatsina** [comment]
great! it works
