### ISSUE TITLE
Push Notification are not coming after update to lower than Android 8 device

### ISSUE THREAD

**Issue by kabirkhaan** [freshdesk/freshchat-android#43]
After updating the library to version `2.4.1` push notifications stop working. If the device is in background. This issue is appearing on devices are lower than `android 8` 

We were using '1.5.2`version before.

**Comment by MuthuFD** [comment]
Hi @kabirkhaan, Are you still facing this issue. We have not made changes to notifications recently. 

1. Is this happening in all device below 8?
2. Is `push notification enabled` true for this user in Web portal?

**Comment by PoriLisa** [comment]
hii, I can see the update of users meta data after refreshing the freshchart.

**Comment by kabirkhaan** [comment]
Hello Lisa,

Thanks for your concern, it's working now but i will update you on Monday

**Comment by MuthuFD** [comment]
@kabirkhaan If you still facing this issue, feel free to reach out to us through support@freshchat.com
