### ISSUE TITLE
When i click onback pressed from the SDK's Shwoconversations Activity and again click the button i am getting the previous conversations.

### ISSUE THREAD

**Issue by jaydesai111** [freshdesk/freshchat-android#44]
using implementation 'com.github.freshdesk:freshchat-android:2.4.1'

**Comment by rameshfreshworks** [comment]
Hi Jay,
Please share the steps to reproduce this issue?

**Comment by jaydesai111** [comment]
Freshchat.getInstance(NapsNibbleApp.getInstance()).identifyUser(authManager.getUserEmail(), "aa58667e-ebf4-4628-a41a-7237650aee39");

**Comment by rameshfreshworks** [comment]
Hi Jay ,

**Comment by rameshfreshworks** [comment]
Hi Jay ,

**Comment by jaydesai111** [comment]
hi

**Comment by jaydesai111** [comment]
is there any place i can share video?

**Comment by rameshfreshworks** [comment]
Hi Jay, 
You can either upload the video to any cloud storage(like Google Drive or Dropbox) and share the link here or drop an email with video attachment to support@freshchat.com

**Comment by MuthuFD** [comment]
Hi @jaydesai111 , I think you need to save restore id to user mapping in your server and provide us the same to restore. Please refer section 3.4 here - https://support.freshchat.com/support/solutions/articles/229319-freshchat-android-sdk-integration-steps

Closing this issue. If you still facing this issue, please reach out to us through support@freshworks.com
