### ISSUE TITLE
Unresolved reference handleFcmMessage

### ISSUE THREAD

**Issue by tjohnn** [freshdesk/freshchat-android#45]
Trying to show a notification in Fcm Service `onMessageReceived()` like
```Freshchat.getInstance(applicationContext).handleFcmMessage(this, remoteMessage)```

The `handleFcmMessage()` seems to be missing from the api and can't be resolved by android studio. I am using freshchat android sdk version `2.5.0`

**Comment by MuthuFD** [comment]
Hi @tjohnn,

Try using 
Freshchat.handleFcmMessage(this, remoteMessage);

**Comment by tjohnn** [comment]
Okay thanks for the quick response. It would be nice if it is updated in docs though.
