### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by vijaemanlapaz** [freshdesk/freshchat-android#46]
Hi,

Whenever i run my application im getting

> Unsupported version of Picasso found. Please create and set custom Image loader using Freshchat.setImageLoader().

Any idea how to fix this??

**Comment by MuthuFD** [comment]
Hi @vijaemanlapaz , 
Freshchat SDK is shipped with Picasso version 2.5.2. This error is thrown if your application is using 2.71828 or any of the newer version.
If you are on any other version of Picasso or if you want to use your own image downloading logic, please refer Section 10 in our documentation https://support.freshchat.com/support/solutions/articles/229319

**Comment by vijaemanlapaz** [comment]
To anybody else experiencing this, you can do the following as a work around if you do not want to change the version of your **Picasso**.

`Freshchat.Freshchat.setImageLoader(com.freshchat.consumer.sdk.j.af.aw(context))`

@MuthuFD thanks for the quick response.

**Comment by abomadi** [comment]
@MuthuFD im facing this issue with Cordova Plugin as well, i cant update the plugin with @vijaemanlapaz solution but i dont know where exactly inside 
`class freshchatPlugin extends CordovaPlugin `
