### ISSUE TITLE
"compile" should be replaced with "implementation"

### ISSUE THREAD

**Issue by eonghk** [freshdesk/freshchat-android#47]
'compile' is deprecated. Please update to 'implementation'.
http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by MuthuFD** [comment]
Hi @eonghk , I hope you are talking about instructions in README. We have updated that.

Closing this issue. If this is not what you mean, feel free to reopen and explain the issue.

**Comment by eonghk** [comment]
I'm talking about this file in your project.
https://github.com/freshdesk/freshchat-android/blob/master/freshchat_sdk/build.gradle
You may try your SDK with a simple project and you will see the warning.

**Comment by MuthuFD** [comment]
Hi @eonghk , Thanks for explaining. 
We will make changes to improve this experience.
