### ISSUE TITLE
How to set user info or user property?

### ISSUE THREAD

**Issue by samosudov** [freshdesk/freshchat-android#48]
version 2.6.0.

MethodNotAllowedException for Freshcaht.setUser() and Freshchat.setUserProperties().

**Comment by MuthuFD** [comment]
@samosudov 
1. If this is a runtime exception, Please share below details
     - Are you using JWT for user authentication 
     - Please share us the complete exception log
     - Please share us the Freshchat config passed to init(). (Remove App id and App key)
     - Is this happening for all user or a particular user?
     - Please share us your Application flow and Freshchat SDK APIs usage.
2. If this is a compile time error, please add try catch around setUser and setUserProperties. This is just a warning.

**Comment by samosudov** [comment]
Thank you! I'll use try-catch
