### ISSUE TITLE
 java.lang.IllegalArgumentException: Unsupported version of Picasso found

### ISSUE THREAD

**Issue by PoriLisa** [freshdesk/freshchat-android#52]
Caused by: java.lang.IllegalArgumentException: Unsupported version of Picasso found. Please create and set custom Image loader using Freshchat.setImageLoader().

**Comment by PoriLisa** [comment]
Freshchat.setImageLoader(Objects.requireNonNull(af.aw(getApplicationContext())));

it was the solution

**Comment by jindalnaveen4** [comment]
Not able to find anything like af.aw......??

**Comment by jindalnaveen4** [comment]
> ```
>  Caused by: java.lang.IllegalArgumentException: Unsupported version of Picasso found. Please create and set custom Image loader using Freshchat.setImageLoader().
> ```

can you please help me on this?

**Comment by rameshfreshworks** [comment]
Freshchat SDK is shipped with Picasso version 2.5.2. This error is thrown if your application is using 2.71828 or any other newer version.
If you are on any other version of Picasso or if you want to use your own image downloading logic, please refer section 10 in our documentation.
https://support.freshchat.com/support/solutions/articles/229319

**Comment by developerjohan01** [comment]
> Freshchat SDK is shipped with Picasso version 2.5.2. This error is thrown if your application is using 2.71828 or any other newer version.
> If you are on any other version of Picasso or if you want to use your own image downloading logic, please refer section 10 in our documentation.
> https://support.freshchat.com/support/solutions/articles/229319
@rameshfreshworks 
The support link above to `229319` is not working... and do you know when support for 2.71828 going to come?

**Comment by rameshfreshworks** [comment]
Hi @developerjohan01 ,
Sorry about the broken link, Here is the updated URL https://support.freshchat.com/en/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps refer to section 8.2 in the document. 
About supporting the latest Picasso version, the new version has breaking changes so support may not be available in the near future.

**Comment by developerjohan01** [comment]
@rameshfreshworks thank you very much for the link. 👍 I will have a look and see if I can make it work. However, I am really using a Cordova/Phonegap plugin which is then using the Freshchat-android project which means that it isn't easy to make code changes because of dependencies... 
The latest version of Picasso has been out for more than 2 years so it is still a bit surprising that you are not using it, breaking changes or not.

**Comment by linndeveloper** [comment]
Caused by: java.lang.IllegalArgumentException: Unsupported version of Picasso found. Please create and set custom Image loader using Freshchat.setImageLoader()
