### ISSUE TITLE
Register the user

### ISSUE THREAD

**Issue by PoriLisa** [freshdesk/freshchat-android#53]
unable to register the user details by using this

FreshchatUser user = Freshchat.getInstance(getApplicationContext()).getUser();
        user.setFirstName("John").setLastName("Doe").setEmail("john@john.doe").setPhone("001", "2542542544");

**Comment by MuthuFD** [comment]
@PoriLisa Are you calling setUser after updating user details?

**Comment by MuthuFD** [comment]
@PoriLisa If you are still facing issues, feel free to post your question and reopen this issue.
You can also reach out to us through support@freshchat.com
