### ISSUE TITLE
Runtime app locale change not working

### ISSUE THREAD

**Issue by codelegger** [freshdesk/freshchat-android#58]
Our App support different locales and user can change locale within App but on Locale change FreshChat Locale has not being changed unless we go to device settings and change Locale from there.
We are following sdk integration step as per this [link](https://support.freshchat.com/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps)
And as described in the section **7.4 Runtime app locale change** of this [link](https://support.freshchat.com/support/solutions/articles/50000000207-freshchat-android-sdk-integration-steps) we tried everything but still its not working Please see my code below.

WebView Listener
````
FreshchatWebViewListener webviewListener = new FreshchatWebViewListener() {
        @Override
        public void onLocaleChangedByWebView(@NonNull WeakReference<Context> activityContext) {
            if (activityContext.get() == null) {
                return;
            }         
            setLocaleCode(localeCode);
        }
    };


//Register Webview listener 
Freshchat.getInstance(this).setWebviewListener(LocaleManager.getInstance().webviewListener)


//Notifying FreshChat on LocaleChnage event
Freshchat.notifyAppLocaleChange(context)

**Comment by rameshfreshworks** [comment]
Hi @codelegger,
Setting run time locale is a bit tricky in android. we would suggest you use the following method for setting runtime locale in the app

public static void changeLocale(Context activityContext, String lang){
  Locale locale = new Locale(lang);
  Resources applicationRes = activityContext.getApplicationContext().getResources();
  DisplayMetrics dm = applicationRes.getDisplayMetrics();
  Configuration conf = applicationRes.getConfiguration();
  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
    conf.setLocale(locale);
  } else {
    conf.locale = locale;
  }
  applicationRes.updateConfiguration(conf, dm);

  Resources activityRes = activityContext.getResources();
  DisplayMetrics dm2 = activityRes.getDisplayMetrics();
  Configuration conf2 = activityRes.getConfiguration();
  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
    conf2.setLocale(locale);
  } else {
    conf2.locale = locale;
  }
  activityRes.updateConfiguration(conf2, dm2);
}

**Comment by codelegger** [comment]
@rameshfreshworks Thanks it works but for arabic RTL not working please see this 
<img width="370" alt="Screen Shot 2019-10-24 at 2 09 21 PM" src="https://user-images.githubusercontent.com/5968581/67458121-f7256c00-f667-11e9-80ac-8b0f52b4d78b.png">

**Comment by rameshfreshworks** [comment]
@codelegger is RTL configuration getting applied for the entire app? or is it only freshchat screens that's not applied?

**Comment by codelegger** [comment]
Its only FreshChat screens not applied. Rest of the App is fine

**Comment by rameshfreshworks** [comment]
Hi @codelegger,
Please contact our support by emailing to support@freshchat.com, We will see how to take this forward by setting up a call or something

**Comment by rameshfreshworks** [comment]
We have fixed a related run time app locale issue in [v3.2.1](https://github.com/freshdesk/freshchat-android/releases/tag/3.2.1). We hope this fixes your issue. 

I am closing this issue now. Feel free to reopen if it does not solve your issue.

**Comment by abhisheksharma18021999** [comment]
how to change locale to show faqs in different languages. ?
is there anu in-bulit function where i can pass locale ????
please help

**Comment by rameshfreshworks** [comment]
Hi @abhisheksharma18021999 ,
Here is the the demo app for handling locale change in Freshchat. Please go through and make the required changes. https://drive.google.com/file/d/1wuwfIVt9O1hOgDIv9bR_2Eyb_2lZ0DO5/view?usp=sharing

**Comment by abhisheksharma18021999** [comment]
thanks alot

**Comment by rickyputrah** [comment]
Trying to change locale using your code shared before @rameshfreshworks but the content of FAQ is not changed. what is changed only button "chat us"?

**Comment by rameshfreshworks** [comment]
Hey @rickyputrah , Have you setup translations for your FAQ's on Freshchat account in the locale you checking ?
