### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by arpitjoshi08** [freshdesk/freshchat-android#6]
E/FRESHCHAT: Exception on LGE Nexus 5X Android API 7.1.1 (25)  getting this error

**Comment by tryprasannan** [comment]
@arpitjoshi08 Can you share more information on when this is happening ? And the Freshchat SDK version where this is happening ?

**Comment by tryprasannan** [comment]
Not enough information to identify or debug the issue. If you have more information, please share.
