### ISSUE TITLE
Loading indefinitely Android SDK 3.0.0

### ISSUE THREAD

**Issue by biancamoreiragyg** [freshdesk/freshchat-android#61]
Hello,

I did a small investigation with the Android SDK and IOS SDK last week using a free account. I used this free account APP Key and APP Id. After that, the company I work for decided to proceed on using FreshChat. Then, I changed to use their APP Key and APP Id and after that I'm stuck on the loading messages screen. I can't test nor doing anything. Both iOS and Android are stuck on the loading screen. Can you please help?

**Comment by MuthuFD** [comment]
@biancamoreiragyg 
As your Freshchat account is present in Freshchat EU server. Freshchat SDK domain should be pointing to Freshchat EU servers. Can you check if this is done right?
​
**Sample code:**
FreshchatConfig freshchatConfig = new FreshchatConfig("APP_ID", "APP_KEY");
freshchatConfig.setDomain("https://msdk.eu.freshchat.com");
Freshchat.getInstance(context).init(freshchatConfig);

**Comment by MuthuFD** [comment]
Freshchat clusters and their SDK domains
US - https://msdk.freshchat.com (default)
AU - https://msdk.au.freshchat.com
EU - https://msdk.eu.freshchat.com
IN - https://msdk.in.freshchat.com
US2 - https://msdk.us2.freshchat.com

**Comment by Softkeydel** [comment]
I have downloaded the sample code and used my appid and appkey but the app stuck on loading

**Comment by Softkeydel** [comment]
I have downloaded the sample code and used my appid and appkey but the app stuck on loading. Please help asap

**Comment by MuthuFD** [comment]
Hi @Softkeydel ,
This can be due to 2 reasons
1. APP ID and APP KEY are wrong or inverted
>You can verify your app id and app key in Mobile SDK page under Settings in your Freshchat portal
2. Freshchat domain is not set in FreshchatConfig
>If you are using https://web.freshchat.com to login, then you need not set domain. If you are using any other url, please contact our support agents to find out your domain. You can reach out to us through support@freshchat.com. You need to set this domain in your FreshchatConfig. Ref: https://github.com/freshdesk/freshchat-android/issues/61#issuecomment-559081352

**Comment by Softkeydel** [comment]
APP ID and APP KEY are ok.

for domain I'm using
IN - https://msdk.in.freshchat.com
Still stuck on loading. Please help

**Comment by Softkeydel** [comment]
APP ID and APP KEY are ok.

for domain I'm using
IN - https://msdk.in.freshchat.com
Still stuck on loading. Please help

**Comment by MuthuFD** [comment]
Hi @Softkeydel , Can you share your Freshchat account number? You can find it in the webpage url.

**Comment by Softkeydel** [comment]
Shall I share it here??

**Comment by Softkeydel** [comment]
> Shall I share it here??



> Shall I share it here??



> Hi @Softkeydel , Can you share your Freshchat account number? You can find it in the webpage url.

Shall I share it here??

**Comment by Softkeydel** [comment]
> Hi @Softkeydel , Can you share your Freshchat account number? You can find it in the webpage url.

Shall I share it here??

**Comment by MuthuFD** [comment]
Hi @Softkeydel , Please share it to support@freshchat.com
