### ISSUE TITLE
Events Timeline

### ISSUE THREAD

**Issue by gilshallem** [freshdesk/freshchat-android#63]
Please add support for "Events Timeline"
It will be very useful to know what the user was doing in the app and even to add crash reports in case the app crashed. 

It will be amazing if the sdk will save the events data locally and then in case the user is opening a ticket all the events will be sent to the server.

Thank you

**Comment by MuthuFD** [comment]
Hi @gilshallem ,
Thanks for the request. 
This feature is already in the works. It should be released in the next 30 days.
Ref: https://github.com/freshdesk/freshchat-android/issues/41

We will keep you posted. Closing this ticket for now.
