### ISSUE TITLE
[Xamarin] Unhandled Exception: Java.Lang.RuntimeException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference

### ISSUE THREAD

**Issue by amoljain99** [freshdesk/freshchat-android#64]
Using update Freshchat library with xamarin android 

Got - 
Unhandled Exception:
Java.Lang.RuntimeException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference

here is full log

12-19 14:01:48.047 V/PhoneWindow(29170): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@2814334[]
12-19 14:01:48.050 D/ViewRootImpl[ChannelListActivity](29170): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
12-19 14:01:48.054 V/PhoneWindow(29170): DecorView setVisiblity: visibility = 0, Parent = ViewRoot{a26dba3 com.nielsen.pinecone/com.freshchat.consumer.sdk.activity.ChannelListActivity,ident = 5}, this = DecorView@2814334[ChannelListActivity]
12-19 14:01:48.058 I/FRESHCHAT_SERVICE(29170): Now Processing b
12-19 14:01:48.060 D/FRESHCHAT(29170): FreshchatUtils::onNetworkConnectivityChanged() called. connected - true
12-19 14:01:48.102 D/Surface (29170): Surface::allocateBuffers(this=0x88027800)
12-19 14:01:48.102 D/Surface (29170): Surface::connect(this=0x88027800,api=1)
12-19 14:01:48.130 I/FRESHCHAT_SERVICE(29170): Now Processing d
12-19 14:01:48.155 D/GraphicBuffer(29170): register, handle(0x87624e40) (w:720 h:1440 s:736 f:0x1 u:b00)
12-19 14:01:48.160 D/HWUIExtension(29170): MTKProgramCache.generateProgram: 562949958664257
12-19 14:01:48.162 D/HWUIExtension(29170): createProgram 0x0002000000500041, binary 0x99a23be3, length 11847, format 37168 within 1477ns
12-19 14:01:48.172 I/FRESHCHAT_SERVICE(29170): Now Processing e
12-19 14:01:48.182 D/GraphicBuffer(29170): register, handle(0x87624e40) (w:720 h:1440 s:736 f:0x1 u:b00)
12-19 14:01:48.198 I/FRESHCHAT_SERVICE(29170): Now Processing m
12-19 14:01:48.198 D/GraphicBuffer(29170): register, handle(0x87624e40) (w:720 h:1440 s:736 f:0x1 u:b00)
12-19 14:01:48.210 I/FRESHCHAT(29170): Processing Backlog : 1 p: 1024
12-19 14:01:48.226 I/FRESHCHAT_SERVICE(29170): Now Processing a
12-19 14:01:48.290 D/Surface (29170): Surface::disconnect(this=0x863d0000,api=1)
12-19 14:01:48.290 D/GraphicBuffer(29170): unregister, handle(0x87624d80) (w:720 h:1344 s:736 f:0x1 u:b00)
12-19 14:01:48.290 D/GraphicBuffer(29170): unregister, handle(0x84bbb240) (w:720 h:1344 s:736 f:0x1 u:b00)
12-19 14:01:48.291 D/GraphicBuffer(29170): unregister, handle(0x86a1d280) (w:720 h:1344 s:736 f:0x1 u:b00)
OnActivityCreated FragmentActivity12-19 14:01:48.337 I/mono-stdout(29170): OnActivityCreated FragmentActivity

12-19 14:01:48.365 I/FRESHCHAT_SERVICE(29170): Now Processing m
12-19 14:01:48.378 I/FRESHCHAT(29170): Processing Backlog : 1 p: 1024
12-19 14:01:48.387 I/FRESHCHAT_SERVICE(29170): Now Processing a
12-19 14:01:48.521 D/miuisdk (29170): current sdk level is 14
12-19 14:01:48.532 I/Android_App_ActivityThread_class_v16(29170): success
12-19 14:01:48.532 I/AppConstants(29170): success
12-19 14:01:48.560 D/FRESHCHAT(29170): FreshchatUtils::onNetworkConnectivityChanged() called. connected - true
12-19 14:01:48.622 V/PhoneWindow(29170): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@a1e55d9[]
12-19 14:01:48.625 D/ViewRootImpl[ConversationDetailActivity](29170): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
12-19 14:01:48.631 V/PhoneWindow(29170): DecorView setVisiblity: visibility = 0, Parent = ViewRoot{77364c com.nielsen.pinecone/com.freshchat.consumer.sdk.activity.ConversationDetailActivity,ident = 6}, this = DecorView@a1e55d9[ConversationDetailActivity]
12-19 14:01:48.634 I/FRESHCHAT_SERVICE(29170): Now Processing b
12-19 14:01:48.638 D/FRESHCHAT(29170): FreshchatUtils::onNetworkConnectivityChanged() called. connected - true
12-19 14:01:48.691 I/FRESHCHAT_SERVICE(29170): Now Processing d
12-19 14:01:48.714 D/Surface (29170): Surface::allocateBuffers(this=0x84867000)
12-19 14:01:48.718 D/Surface (29170): Surface::connect(this=0x84867000,api=1)
12-19 14:01:48.724 I/FRESHCHAT_SERVICE(29170): Now Processing c
12-19 14:01:48.759 D/AndroidRuntime(29170): Shutting down VM
12-19 14:01:48.761 E/AndroidRuntime(29170): FATAL EXCEPTION: main
12-19 14:01:48.761 E/AndroidRuntime(29170): Process: com.nielsen.pinecone, PID: 29170
12-19 14:01:48.761 E/AndroidRuntime(29170): java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at com.freshchat.consumer.sdk.activity.ConversationDetailActivity.onCreateOptionsMenu(Unknown Source:31)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.app.Activity.onCreatePanelMenu(Activity.java:3442)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:340)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:93)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:332)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.support.v7.app.AppCompatDelegateImplV9.preparePanel(AppCompatDelegateImplV9.java:1358)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.support.v7.app.AppCompatDelegateImplV9.doInvalidatePanelMenu(AppCompatDelegateImplV9.java:1638)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.support.v7.app.AppCompatDelegateImplV9$1.run(AppCompatDelegateImplV9.java:134)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.os.Handler.handleCallback(Handler.java:790)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.os.Looper.loop(Looper.java:171)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at android.app.ActivityThread.main(ActivityThread.java:6656)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at java.lang.reflect.Method.invoke(Native Method)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
12-19 14:01:48.761 E/AndroidRuntime(29170): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
12-19 14:01:48.787 W/System  (29170): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
12-19 14:01:48.789 I/System.out(29170): e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
12-19 14:01:48.790 I/System.out(29170): [OkHttp] sendRequest>>
12-19 14:01:48.792 I/System.out(29170): [OkHttp] sendRequest<<
12-19 14:01:48.797 W/System  (29170): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
12-19 14:01:48.799 I/System.out(29170): e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
12-19 14:01:48.897 W/System  (29170): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
12-19 14:01:48.901 I/System.out(29170): e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
12-19 14:01:49.353 I/System.out(29170): [OkHttp] sendRequest>>
12-19 14:01:49.355 I/System.out(29170): [OkHttp] sendRequest<<
12-19 14:01:49.943 I/FRESHCHAT_SERVICE(29170): Now Processing e
Unhandled Exception:

Java.Lang.RuntimeException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference

**Comment by rameshfreshworks** [comment]
Hi,
 Please provide us the following details to debug this issue at our end
1. Are you using xamarin.forms or xamarin.native for implementation?
2. Share us Freshchat SDK version that you are using

**Comment by amoljain99** [comment]
Hi Ramesh 
we are using xamarin native with xamarin android and xamarin ios
and we are using  freshchat-android-3.0.0.aar

**Comment by rameshfreshworks** [comment]
Hi @amoljain99 ,
Can you share us dependencies and dependency graph that the android app uses?

**Comment by MuthuFD** [comment]
Closing this ticket.
If the issues still persists, share above details and reopen.
