### ISSUE TITLE
[Xamarin] Unread message count not working

### ISSUE THREAD

**Issue by amoljain99** [freshdesk/freshchat-android#65]
Using update frechat library for xamarin Android 
Trying with below method 
   Freshchat.GetInstance(context).GetUnreadCountAsync(this);
every time it get 0 count

created broadcast with intent action for getting unread count it does not work

private class FreshchatBroadcastReceiver : BroadcastReceiver
        {
            #region API
            /// <summary>
            /// Register this instance.
            /// </summary>
            public void Register()
            {
                var manager = wManager.Target;

                if (manager != null)
                {
                    var filter = new IntentFilter();

                    filter.AddAction(Freshchat.FreshchatUserRestoreIdGenerated);
                    filter.AddAction(Freshchat.FreshchatUnreadMessageCountChanged);

                    LocalBroadcastManager.GetInstance(manager.context).RegisterReceiver(this, filter);
                }
            }

            /// <summary>
            /// Unregister this instance.
            /// </summary>
            public void Unregister()
            {
                var manager = wManager.Target;

                if (manager != null)
                {
                    LocalBroadcastManager.GetInstance(manager.context).UnregisterReceiver(this);
                }
            }
            #endregion

            #region Overrides
            /// <summary>
            /// This method is called when the BroadcastReceiver is receiving an Intent
            ///  broadcast.
            /// </summary>
            /// <param name="context">The Context in which the receiver is running.</param>
            /// <param name="intent">The Intent being received.</param>
            public override void OnReceive(Context context, Intent intent)
            {
                Utilities.ConsoleLog("[FreshchatBroadcastReceiver] OnReceive: " + intent.Action);

                var manager = wManager.Target;

                if (manager != null)
                {
                    if (Freshchat.FreshchatUserRestoreIdGenerated.Equals(intent.Action))
                    {
                        manager.CheckFreshChatRestoreId();
                    }
                    else if (Freshchat.FreshchatUnreadMessageCountChanged.Equals(intent.Action))
                    {
                        manager.CheckFreshChatUnreadMessagesCount();
                    }
                }
            }
            #endregion

            #region Construction
            /// <summary>
            /// Initializes a new instance of the <see cref="FreshchatBroadcastReceiver"/> class.
            /// </summary>
            /// <param name="manager">Freshchat manager.</param>
            public FreshchatBroadcastReceiver(FreshChatManager manager)
            {
                wManager = new PineconeWeakReference<FreshChatManager>(manager);
            }
            #endregion

            #region Private fields
            private readonly PineconeWeakReference<FreshChatManager> wManager;
            #endregion
        }

**Comment by rameshfreshworks** [comment]
Hi,
We would suggest registering the broadcast receiver in the Application class for both unread messages count and restore id. You can check for the unread messages count by calling getUnreadCountAsync() API and the result is returned in the callback.

**Comment by amoljain99** [comment]
Hi ramesh 
we have same scenario for ios also can you please add suggestion for ios xamarin code to get unread message

**Comment by rameshfreshworks** [comment]
in iOS, you can use unreadCountWithCompletion() API and the result is returned in the callback.

**Comment by SergeyUsov** [comment]
Hi @rameshfreshworks ,

I registered a broadcast receiver in Application. But it doesn't work.

1. I am receiving com.freshchat.consumer.sdk.MessageCountChanged action in the receiver only when Conversation screen is opened.
2. I can not receive any messages when Converstation screen is not opened. But the application is still running and another screen is in foreground.

From logs I can see:
FRESHCHAT_SERVICE is launched only when ConversationDetailActivity is created. I suppose FRESHCHAT_SERVICE is responsible for sending broadcast intents about message count is changed. But this service doesn't work when ConversationDetailActivity  is not created.

Could you please fix the issue?

With best regards,
Sergey

**Comment by rameshfreshworks** [comment]
Hi @SergeyUsov ,
Messages fetch would happen in the Channel listing screen(Shown if you have multiple channels)  and ConversationDetailActivity.  MessageCountChanged broadcast will be when message fetch call response has new messages in it.  
To receive the messages instantly we recommend you integrate firebase notification service.

**Comment by SergeyUsov** [comment]
Hi @rameshfreshworks,

So registering broadcast receiver is useless if Conversation screen is not opened.
We can not receive any messages via broadcast receiver  if Conversation screen is not opened.
Please confirm this. 

With best regards,
Sergey

**Comment by SergeyUsov** [comment]
Hi @rameshfreshworks,
Let me try to implement push notifications. Will notify about results!

**Comment by SergeyUsov** [comment]
Hi @rameshfreshworks ,

I have implemented firebase notification service.
I registered broadcast receiver in Application class.

But it doesn't work.
I am not receiving com.freshchat.consumer.sdk.MessageCountChanged actions when Conversation screen is not opened.
So I can not track unread message counter is changed outside of Conversation screen.
Attached the android studio project with firebase notification implementation.

[freshchat-android-master_push.zip](https://github.com/freshdesk/freshchat-android/files/3987999/freshchat-android-master_push.zip)
Could you check the attach and help me with this?

**Comment by amoljain99** [comment]
@rameshfreshworks Any update for this issue

**Comment by rameshfreshworks** [comment]
Hi @amoljain99 ,
I hope you have implemented FCM correctly, Are you receiving notifications for messages sent from agent portal?
Refer [this document](https://support.freshchat.com/support/solutions/articles/231986-android-push-notifications-are-not-working-how-do-i-fix-this-) for troubleshooting .

**Comment by SergeyUsov** [comment]
Hi @rameshfreshworks ,
@amoljain99 

After adding FCM key in Freshchat Settings > Mobile SDK on web interface it works fine. We receive notifications properly.
Thanks for your help!
