### ISSUE TITLE
[Question] launchActivityOnFinish doesn't have support for bundle?

### ISSUE THREAD

**Issue by andreservidonigyg** [freshdesk/freshchat-android#71]
Hello everyone. I'm trying to check if the user interacted with the notification from SDK but i don't see any option to add a bundle so i can see if user get out from chat activity or not. 
Is there any other way?

Thanks.

**Comment by rameshfreshworks** [comment]
Hi @andreservidonigyg , 
We would like to understand the use-case that you are trying to solve. Can you please provide us more info on that?

**Comment by andreservidonigyg** [comment]
Hello @rameshfreshworks thanks for the reply :) I just want to check if the activity launched by the freshchat, after it handle the notification click, can have a bundle. So with this i can know from where my activity was opened.

**Comment by rameshfreshworks** [comment]
Hi @andreservidonigyg ,
Sorry, We do not have support for your request. Here is the workaround we would like to suggest. 
Let's say ActivityA is the one set as Fallback activity using FreshchatNotificationConfig.launchActivityOnFinish(). Where ever you launch ActivityA in your app, you can pass an intent extra to differentiate between Freshchat launch and your app launch.

**Comment by andreservidonigyg** [comment]
@rameshfreshworks Thanks for the reply! I'm going to do something like this. 
:D
