### ISSUE TITLE
Changing the language to Portuguese at runtime does not work Android 8.1

### ISSUE THREAD

**Issue by gettoAndro** [freshdesk/freshchat-android#76]
I am trying to change the language to Portuguese, Italian on Android 8.1, but it does not work. Changing the language to French, German, English, Russian works and works on Android 7 and below with Portuguese

```
@TargetApi(Build.VERSION_CODES.N)
    private fun updateResources(context: Context, locale: DTDLocale): Context {
        val contextLocale = createLocale(locale)
        Locale.setDefault(contextLocale)

        val configuration = context.resources.configuration
        configuration.setLocale(contextLocale)

        return context.createConfigurationContext(configuration)
    }

    @Suppress("DEPRECATION")
    private fun updateResourcesLegacy(context: Context, locale: DTDLocale): Context {
        val contextLocale = createLocale(locale)
        Locale.setDefault(contextLocale)

        val resources = context.resources

        val configuration = resources.configuration
        configuration.locale = contextLocale

        resources.updateConfiguration(configuration, resources.displayMetrics)

        return context
    }

private fun createLocale(locale: DTDLocale): Locale {
        return when(locale){
            DTDLocale.PT -> Locale(locale.language, "BR")
            else -> Locale(locale.language)
        }
    }

```

Only works with code pt-BR on android version 7 and below. 
Another nuance on Android 8.1 is changing the language to Portuguese if i exit the application and start it again. I using 3.0.0 version FreshChat
I tested on Xiaomi Redmi 5Plus and emulator Nexus 5

**Comment by rameshfreshworks** [comment]
Hi @gettoAndro 

Here is the [demo app](https://www.dropbox.com/s/i4hee0c9pqaxq6k/FreshchatLocaleDemo.zip) for run time app locale change. Please refer and make the required changes.

**Comment by gettoAndro** [comment]
Hi @rameshfreshworks . I try using this code but still not work
https://www.dropbox.com/s/i4hee0c9pqaxq6k/FreshchatLocaleDemo.zip?file_subpath=%2FFreshchatLocaleDemo%2Fapp%2Fsrc%2Fmain%2Fjava%2Fcom%2Fexample%2Fdemoandroidx%2FLocaleUtils.java

**Comment by rameshfreshworks** [comment]
Hi @gettoAndro, 
We are adding improvements for run-time locale support. Can you check the behaviour with our beta release by replacing the freshchat 3.0.0 with following 

`implementation 'com.github.freshdesk:freshchat-android:runtime-locale-SNAPSHOT'` 

Let us know if this fixes your problem. 

Note: We suggest not to use this in production as this not official release.

**Comment by gettoAndro** [comment]
Hello @rameshfreshworks 
I using `implementation 'com.github.freshdesk:freshchat-android:runtime-locale-SNAPSHOT'`
But still, when changing the language to Portuguese in the application on Android 8.1, the language does not change to Portuguese but to English. Only when i select Portuguese and exit the application then restart it, is everything okay

**Comment by rameshfreshworks** [comment]
Hi @gettoAndro 
We are unable to reproduce this at our end. Can you share a demo project in which we can reproduce this behaviour?

**Comment by gettoAndro** [comment]
@rameshfreshworks 
Sorry to bother you, I could find the problem and fix it. Works fine with implementation 'com.github.freshdesk:freshchat-android:3.0.0' . I just didn’t notice that I have overridden the method in App. 

```
 override fun getResources(): Resources {
        // Localising app resources for in-app locale changes
        return contextLocalizer.getLocalisedResources(super.getResources())
    }
```

And in this method, resources (strings.xml for pt-BR doesn't exist) were returned
