### ISSUE TITLE
First Time of install app Channel List not displaying

### ISSUE THREAD

**Issue by mayurrathod27** [freshdesk/freshchat-android#77]
Hello 
   i done following code for restore id and conversation but when i install app then first time conversation not load after that all time conversation shows perfectly.

please know why it happen

FreshchatConfig freshchatConfig = new FreshchatConfig("xxxxxxx",
        "yyyyyyy");
freshchatConfig.setCameraCaptureEnabled(false);
freshchatConfig.setGallerySelectionEnabled(true);

Freshchat.setImageLoader(new CustomImageLoader());
Freshchat.getInstance(getApplicationContext()).init(freshchatConfig);

SharedPreferences prefs2 = getSharedPreferences("freshchat_id", MODE_PRIVATE);
String freshchat_id = prefs2.getString("restoreid", "");

if(freshchat_id.equalsIgnoreCase("") || freshchat_id==null)
{
    try {
        Freshchat.getInstance(getApplicationContext()).identifyUser(email, null);
    } catch (MethodNotAllowedException e) {
        e.printStackTrace();
    }

    FreshchatUser user = Freshchat.getInstance(getApplicationContext()).getUser();
    user.setFirstName(fname).
            setLastName(lname).
            setEmail(email).
            setPhone("+" + code, mobile);
    try {
        Freshchat.getInstance(getApplicationContext()).setUser(user);
    } catch (MethodNotAllowedException e) {
        e.printStackTrace();
    }
    Freshchat.showConversations(SupportActivity.this);

}
else
{
    try {
        Freshchat.getInstance(getApplicationContext()).identifyUser(email,freshchat_id);
    } catch (MethodNotAllowedException e) {
        e.printStackTrace();
    }
    Freshchat.showConversations(SupportActivity.this);

}

**Comment by rameshfreshworks** [comment]
Hi @mayurrathod27,

Looks like you are performing both Freshchat.init() and Freshchat.showConversations() after chat option is selected. Freshchat requires some time to load all the data in the very first init. That is the reason why you are seeing a loading indicator in the very first launch.

Instead we would recommend you to do the following,

Let's say you are showing chat option in ActivityA,  Perform Freshchat.init(), identifyUser() in onCreate() of the activity and call Freshchat.showConversations() on chat option click.
