### ISSUE TITLE
Method's getUnreadCountAsync callback is not executed when called from onResume

### ISSUE THREAD

**Issue by angelix** [freshdesk/freshchat-android#89]
Maybe related with #78 when running **getUnreadCountAsync** method in onResume, i never get a response in the callback in the first run. Only if i move the app to the background and restore it, the onResume method will be executed once more, only then i get a response in the callback.

**Comment by rameshfreshworks** [comment]
@angelix That's strange. Reach out to support@freshchat.com if you still need assistance.

**Comment by bboyzlodey** [comment]
@angelix I detect that if initial processes for instance Freshchat not finished and you called getUnreadCountAsync, then you will not give response.

As solution, you can execute method delay about 3 seconds (test it on different devices):
```java     
       Handler handler = new Handler();
       handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                Log.d("HomeActivity", "Start unread runnable");
                Freshchat.getInstance(getApplicationContext()).getUnreadCountAsync(callback);
            }
        }, 3 * 1000);
```

@rameshfreshworks I tested calling method getUnreadCountAsync inside onCreate method MainActivity class. Results between 3.0.0 and 3.6.5 versions are different. On 3.0.0 version getUnreadCountAsync callback may be will executed (dependent of device). Initial block was been:

```java
 private void initialiseFreshchat() {

        FreshchatConfig freshchatConfig = new FreshchatConfig(appId, appKey);
        getFreshchatInstance(getApplicationContext()).init(freshchatConfig);

    }
```
