### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rahuldange09** [freshdesk/freshchat-android#92]
Hello,
I would like to ask that
I should initialize freshchat everytime app launches or just once when user logins the app (only one time call after login.. nothing after relaunching app).

**Comment by MuthuFD** [comment]
@rahuldange09 We recommend you to initialise SDK once per launch of application.
You can choose to initialise on app launch or before sdk use. 
Please make sure SDK has few seconds between init and sdk screen launch. This is needed for SDK to show updated content.

If you have more questions, mail us at support@freshchat.com
